### ISSUE TITLE
開催種目

### ISSUE THREAD

**Issue by 3846masa** [post-internet/year-end-s-hack-day-2014#2]
- [x] LT
- [ ] Hackathon
  - 内容未定
- [x] CTF #3 
  - やります！
  - 採点サーバとか立ててやりたいかもね
- [ ] 競技プログラミング
  - judgeシステムが楽に構築できるとベスト

**Comment by mactkg** [comment]
LTするならネタなんかあると思います

**Comment by 3846masa** [comment]
今回はLTとCTFというとこで．
