### ISSUE TITLE
開催場所

### ISSUE THREAD

**Issue by 3846masa** [post-internet/year-end-s-hack-day-2014#6]
そういえば，場所かんがえてなかった....
6階のクロスフィールドラウンジとか借りるとかかな...？

**Comment by mactkg** [comment]
やるなら、早めに押さえたほうが良いと思う。もしかしたらサークルの設立を素早くやってしまったほうがいいかもという気持ちはある。

**Comment by 3846masa** [comment]
今週中に日程決めてしまって場所取ったほうがいいか....？ #1 
サークル設立したら，場所取りやすいんかな？

**Comment by mactkg** [comment]
@3846masa サークル名義で借りられるので、イベントとして借りやすい気がする。他の方法だと、先生とかに協力してもらえないと出来ない気がする

**Comment by 3846masa** [comment]
23日と24日に6階のクロスフィールドラウンジを取りたい
最悪どちらか片方でもいい
