### ISSUE TITLE
LTの準備

### ISSUE THREAD

**Issue by 3846masa** [post-internet/year-end-s-hack-day-2014#9]
- [ ] テーマ
  -  決めても決めなくとも
- [ ] 時間
  - 3分〜5分で決めたい？
- [ ] その他
  - ベストLT賞を決めたい
    - 投票制
      - https://github.com/adambutler/poll

**Comment by mactkg** [comment]
投票システムこんなのはどうか。
http://poll.lab.io/

**Comment by 3846masa** [comment]
見た目キレイでよい
けど，投票結果は最後まで非表示にしたい感

**Comment by mactkg** [comment]
Rubyのシステムで公開されているので、そういうことは出来ると思う。
https://github.com/adambutler/poll

**Comment by 3846masa** [comment]
なるほど
